default_deploy_mode = "upload"

# This section sets build options; uncomment if you need to set any of these.
# They can also be overridden by individiual deployment modes if needed!

# [build]
# # allowed values are "world" and "arena"
# build_mode = "world"
# # allowed values are "release", "dev", and "profiling"
# build_profile = "release"
# # defaults to the name of your crate from Cargo.toml
# out_name = "my_crate_name"
# # any additional flags that you'd like to be passed to wasm-pack
# extra_options = []


# Add any number of deployment modes below.
# When deploying, select which mode to use with `cargo screeps deploy -m modename`
# Each mode requires at least a destination (to deploy to a filesystem path), or authentication
# credentials (to upload to a server via API), which can be either an auth_token or
# username and password.

[upload]
auth_token = "your auth token"
# # or, if you're using instead of auth_token:
# username = "your username or email"
# password = "your password"
# # The following are the default values for the optional upload options, uncomment to change
# branch = "default"
# # include all wasm and js files from these directories (use absolute or relative paths)
# include_files = ["pkg", "javascript"]
# hostname = "screeps.com"
# ssl = true
# port = 443
# # This option has no default - any string value will set a path prefix in the API URL,
# # such as "ptr" and "season" to reach the APIs of those environments
# prefix = "url_prefix"

# [copy]
# destination = "your copy destination without the branch directory"
# # The following are the default values for the optional copy options, uncomment to change
# branch = "default"
# include_files = ["pkg", "javascript"]
# prune = false
# # Override global build section items for any mode, if needed
#   [copy.build]
#   extra_options = ["--features=private-server"]

# [ptr]
# auth_token = "your auth token"
# prefix = "ptr"

# [season]
# auth_token = "your auth token"
# prefix = "season"
#   [season.build]
#   extra_options = ["--features=my-crate-season-1-feature"]
